AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Lambda Adapter (x86_64) - Run web applications on AWS Lambda

Resources:
  LambdaAdapterLayerX86:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: .
      CompatibleRuntimes:
        - nodejs14.x
        - nodejs12.x
        - python3.9
        - python3.8
        - python3.7
        - python3.6
        - ruby2.7
        - java11
        - java8.al2
        - java8
        - go1.x
        - dotnet6
        - dotnetcore3.1
        - provided.al2
        - provided
      Description: 'Layer for AWS Lambda Adapter x86_64'
      LicenseInfo: 'Available under the Apache-2.0 license.'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64

  LayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref LambdaAdapterLayerX86
      Principal: *

Outputs:
  LambdaAdapterLayerX86Arn:
    Description: "arn for LambdaAdapterLayerX86"
    Value: !Ref LambdaAdapterLayerX86
