AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lwa-streaming-response-demo-nextjs

  Sample SAM template for lwa-streaming-response-demo-nextjs
Globals:
  Function:
    Timeout: 60

Resources:
  StreamingNextjsFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 256
      PackageType: Image
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: AWS_IAM
        InvokeMode: RESPONSE_STREAM
    Metadata:
      DockerTag: v1
      DockerContext: ./
      Dockerfile: Dockerfile

Outputs:
  StreamingNextjsFunctionOutput:
    Description: "Streaming Nextjs Function ARN"
    Value: !GetAtt StreamingNextjsFunction.Arn
  StreamingNextjsFunctionUrlOutput:
    Description: "nextjs streaming response function url"
    Value: !GetAtt StreamingNextjsFunctionUrl.FunctionUrl