AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bun graphql response streaming

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  BunGraphqlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: app/
      Handler: run.sh
      Runtime: provided.al2023
      Architectures:
        - arm64
      MemorySize: 256
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          AWS_LWA_INVOKE_MODE: response_stream
          PORT: 3000
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerArm64:24
        - !Sub arn:aws:lambda:us-east-1:582637575117:layer:BunRuntimeArm64:1
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

Outputs:
  BunGraphqlFunctionUrl:
    Description: "Function URL for Bun Graphql function"
    Value: !Join 
      - ''
      - - !GetAtt BunGraphqlFunctionUrl.FunctionUrl
        - 'graphql'
  BunGraphqlFunction:
    Description: "Bun Graphql Lambda Function ARN"
    Value: !GetAtt BunGraphqlFunction.Arn
