[book]
authors = ["AWS Lambda Web Adapter Contributors"]
language = "en"
multilingual = false
src = "src"
title = "AWS Lambda Web Adapter"

[build]
build-dir = "../../docs-site"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/awslabs/aws-lambda-web-adapter"
git-repository-icon = "fa-github"
site-url = "/aws-lambda-web-adapter/"
additional-css = ["theme/custom.css"]
additional-js = []
no-section-label = false
cname = ""

[output.html.fold]
enable = true
level = 1
