AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-php-demo

  Sample SAM Template for serverless-php-demo

Globals:
  Function:
    Timeout: 10

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      EndpointConfiguration:
        Type: REGIONAL
      StageName: Prod
      TracingEnabled: True
      BinaryMediaTypes:
        - '*~1*'
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      MemorySize: 2048
      Architectures:
        - x86_64
      Handler: bootstrap
      Runtime: provided.al2
      Environment:
        Variables:
          RUST_LOG: debug
          PORT: 8080
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:25
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:Php82FpmNginxX86:13
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
        Proxy:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  URL:
    Description: "API Gateway endpoint URL for Prod stage for PHP application"
    Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  Function:
    Description: "Lambda Function ARN"
    Value: !GetAtt Function.Arn
