AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Hello World with Lambda Web Adapter

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Architectures:
      - arm64

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        ApiEvents:
          Type: HttpApi
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: hello-world-lambda

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  HelloWorldFunction:
    Description: Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
